#!/bin/sh

if [ ! -f /opt/etc/dropbear/dropbear_rsa_host_key ]; then
    /opt/bin/dropbearkey -t rsa -f /opt/etc/dropbear/dropbear_rsa_host_key
fi

if [ ! -f /opt/etc/dropbear/dropbear_ecdsa_host_key ]; then
    /opt/bin/dropbearkey -t ecdsa -f /opt/etc/dropbear/dropbear_ecdsa_host_key
fi

if [ ! -f /opt/etc/dropbear/dropbear_ed25519_host_key ]; then
    /opt/bin/dropbearkey -t ed25519 -f /opt/etc/dropbear/dropbear_ed25519_host_key
fi
